export const CREATE_DETAILS_START = "CREATE_DETAILS_START";
export const CREATE_DETAILS_SUCCESS = "CREATE_DETAILS_SUCCESS";
export const CREATE_DETAILS_ERROR = "CREATE_DETAILS_ERROR";

export const FETCH_DETAILS_START = "FETCH_DETAILS_START";
export const FETCH_DETAILS_SUCCESS= "FETCH_DETAILS_SUCCESS";
export const FETCH_ARTIST_SUCCESS= "FETCH_ARTIST_SUCCESS";
export const FETCH_ERROR = "FETCH_DETAILS_ERROR";

export const UPDATE_DETAILS_START = "UPDATE_DETAILS_START";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
export const UPDATE_DETAILS_ERROR = "UPDATE_DETAILS_ERROR";

export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const DELETE = 'DELETE';