export const FETCH_DETAILS_START = "FETCH_DETAILS_START";
export const FETCH_DETAILS_SUCCESS= "FETCH_DETAILS_SUCCESS";
export const FETCH_ARTIST_SUCCESS= "FETCH_ARTIST_SUCCESS";
export const FETCH_ERROR = "FETCH_DETAILS_ERROR";